version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-stretch
    steps:
      - run:
          command: mvn clean verify
      - when:
          condition:
            equal: [circleci-project-setup, << pipeline.git.branch >>]
          steps:
            - run:
                command: mvn sonar:sonar -Dsonar.login=${SONAR_TOKEN} -Dsonar.projectKey="camel-lsp-client-eclipse" -Dsonar.projectName="Eclipse Client for Apache Camel Language Server";



workflows:
  camel-lsp-client-eclipse:
    jobs:
      - build:
          context: sonarcloud

