version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-stretch
    steps:
      - run:
          command: mvn clean verify
      - when:
          condition:
            equal: [master, << pipeline.git.branch >>]
          steps:
            - sonarcloud/scan



workflows:
  camel-lsp-client-eclipse:
    jobs:
      - build

